apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaler-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: scaler-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: scaler-operator-role
  apiGroup: rbac.authorization.k8s.io
